# -*- coding: utf-8 -*-
"""Morphological Analyzer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SPVahfNdiTJ53wBit8S1_wrIiyvyRuVD
"""

#Name: D. Chandra Babu
#Reg.no:18ihmt15
from google.colab import drive
drive.mount('/content/drive')

#chandu
import re
import sys
with open("/content/drive/My Drive/chandu/cl/telugu/Telsuff.txt") as sf:
  suffixes=sf.read().split("\n")
print(suffixes)
with open("/content/drive/My Drive/chandu/cl/telugu/Telbase.txt") as bs:
  bases=bs.read().split("\n")
#print(bases)
with open("/content/drive/My Drive/chandu/cl/telugu/Telroot.txt") as rt:
  roots=rt.read().split("\n")
  #print(roots)
#print(roots)
# base.txt is converted as ’dictionary’ variable with key and value, Key is the base form a nd the value is the root form
#base=https://drive.google.com/file/d/19ZyjXh_6247x2gs1aUb7HDELmaghX96E/view?usp=sharing
#suffix=https://drive.google.com/file/d/1DsYS7KZe7S3vJhLQhwqVNOlYTZCEZPR-/view?usp=sharing
#root=https://drive.google.com/file/d/1mQFc8aaZyD3TufJSYjPcluQlkwKvnJYu/view?usp=sharing
base_dict={}
for base in bases:
  if (base != ""):
    base=base.split(",")
    base_dict[base[1]] = base[0]
print (base_dict)


# root.txt is converted as ’dictionary’ variable with key and value, Key is the root forma nd the value is given as 1

root_dict={}
for root in roots:
  if (root != ""):
    root_dict[root] = 1

print (root_dict)
plural=input("Enter the plural noun: ")
# The function "morph_anal" is built with the following logic
#1. The ending of input word is matched with the suff.txteng-analyzer-sample.py Thu May 06 09:07:56 2021 2
#2. If found, the suffix is chopped and the remaining portion is called as base #3. Thebase is matched with base_hash, if it is available, the value (i.e. root) is id entified
#4. The identified root is matched with root_hash for its validity, if it is available,then root and suffix are returned.
def morph_anal(plural):
  for suffix in suffixes:
    if(re.search(suffix+'$',plural)):
      base=re.sub(suffix+'$',"",plural)
      if base in base_dict:
        root=base_dict[base]
        if root in root_dict:
          return root, suffix
        else:
          return "not found in base_dict"
    else:
      return "not found in root_dict"



while(plural):
  singular=morph_anal(plural)
  print("The composition of",plural,"is",singular)
  choice= input("Do you want to continue [Y|N]: ")
  if(choice == "Y"):
    plural=input("Enter the plural noun: ")
  else:
    break